name: Check for Merge Conflicts

on: [push]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for merge conflict markers
        run: |
          echo "Checking for Conflict markers in markdown files (.md)..."

          conflicts=$(grep -rnH '<<<<<<<\|=======\|>>>>>>>' --include=\*.md . || true)
          if [ -n "$conflicts" ]; then
            echo "Merge conflict markers were found in files. Please remove them:"
            echo -e "*************************\033[31m\n$conflicts\n\033[0m*************************"
            exit 1
          else
            echo -e "No marker found! \033[32mPassed\033[0m"
          fi
