name: Check for Merge Conflicts

on: [push]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for merge conflict markers
        run: |
          echo "Checking for Conflict markers in markdown files (.md)..."

          mapfile -t conflicts < <(grep -rnH '<<<<<<<\|=======\|>>>>>>>' --include=\*.md . || true)

          if [ ${#conflicts[@]} -gt 0 ]; then
            echo -e "Merge conflict markers found in Markdown files. Please remove them:"
            echo "*************************************************************"
            echo ""
            echo 
            for conflict in "${conflicts[@]}"; do
              # Split the output into file, line number, and text
              IFS=":" read -r file line_number line_text <<< "$conflict"

              echo -e "\033[31m$file(line: $line_number): $line_text\033[0m"
            done
            echo ""
            echo "*************************************************************"
            exit 1
          else
            echo "No merge conflict markers found."
          fi
