name: Check for Merge Conflicts

on: [push]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for merge conflict markers
        run: |
          conflicts=$(grep -rnH '<<<<<<<\|=======\|>>>>>>>' --include=\*.md . || true)
          if [ -n "$conflicts" ]; then
            echo "Merge conflict markers found in Markdown files. Please resolve the following conflicts before pushing:"
            echo "$conflicts"
            exit 1
          else
            echo "No merge conflict markers found."
          fi
